#!/bin/sh
### BEGIN INIT INFO
# Provides:          vibe_ageing_app
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start vibe ageing app python daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

DIR=/home/orangepi/camera-ageing-test-app
DAEMON=$DIR/ageing_app.py
DAEMON_OPTS="--serial_port /dev/ttyS5 --config $DIR/config/vibe-c1b-4h-ageing.cfg"
DAEMON_USER=root
DAEMON_NAME=vibe_ageing_app
PIDFILE=/var/run/$DAEMON_NAME.pid

# Use python from the virtual environment
PYTHON_EXEC=/home/orangepi/vibe-env/bin/python3
# Add python executable to DAEMON
DAEMON="$PYTHON_EXEC $DAEMON"
LOG_FILE="/var/log/vibe_ageing_app.log"
# touch log file
if [ ! -f $LOG_FILE ]; then
    touch $LOG_FILE
    chown orangepi $LOG_FILE
    chmod 664 $LOG_FILE
fi

do_start () {
    chown orangepi $DIR
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    echo "Starting system $DAEMON_NAME daemon" >> $LOG_FILE
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile \
        --user $DAEMON_USER --chuid $DAEMON_USER \
        --exec /bin/bash -- -c "source /home/orangepi/vibe-env/bin/activate && 
        $DAEMON $DAEMON_OPTS >> $LOG_FILE 2>&1"
    log_end_msg $?
}

do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    echo  "Stopping system $DAEMON_NAME daemon" >> $LOG_FILE
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0


